//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Efficio {
  public static SWIGTYPE_p_namespace Efficio {
    set {
      EfficioPINVOKE.Efficio_set(SWIGTYPE_p_namespace.getCPtr(value));
      if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_namespace ret = new SWIGTYPE_p_namespace(EfficioPINVOKE.Efficio_get(), true);
      if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}
